export const siteConfig = {
  title:
    'Yash Kapure | Best Freelancer | Front-End Engineer | MERN/MEVN Stack Dev | Full Stack Web Developer | React-Native Developer',
  description:
    'Frontend & full-stack developer available for US and global clients. React, Next.js, MERN/MEVN. Remote work, flexible hours, USD rates. Hire for production-ready web apps, performance, and SEO.',
  keywords: [
    // US-focused (for discoverability and clients)
    'Hire React developer USA',
    'Hire Next.js developer United States',
    'Freelance web developer US',
    'Full stack developer USA',
    'Remote web developer United States',
    'React developer for hire US',
    'Next.js developer USA',
    'MERN stack developer United States',
    'Frontend developer USA remote',
    'Web developer US freelance',
    'SEO AEO GEO',
    'SEO AEO GEO Production Readiness',
    'Answer Engine Optimization',
    'Generative Engine Optimization',
    'Structured data JSON-LD',
    'Online Interview Assessment System for Students and Professionals',
    'Yash Kapure projects',
    'Projects by Yash Kapure',
    'Yash Kapure',
    'Contact Yash Kapure',
    "Dr. Manisha's Yoga Institute is Developed by Yash Kapure",
    'Anandlok Ayurveda is Developed By Yash Kapure',
    'Anandlok Ayurveda',
    "Dr. Manisha's Yoga Institute",
    'Projects of Yash Kapure',
    'Best Freelancer Near me',
    'Affordable Freelancer Near me',
    'Hourly based paid freelancer near me',
    'React-Native Developer near me',
    'React.js Developer Near me',
    'Next.js Developer Near me',
    'Yash Vinod Kapure',
    'Best Freelancer',
    'Front-End Engineer',
    'MERN/MEVN Stack Dev',
    'Full Stack Web Developer',
    'Front-end React-Native Developer',
    'Freelance web development',
    'React-Native development services',
    'MERN Stack projects',
    'MEVN Stack development',
    'Web development portfolio',
    'Yash Kapure portfolio',
    'Freelancer services',
    'Full Stack Developer',
    'Who is Yash Kapure?',
    'Where does yash Kapure Live?',
    'Web Developer Near me',
    'Front-End Developer near me',
    'Domain Name purchase',
    'Top-rated freelancer',
    'Expert web developer',
    'Skilled React-Native Developer',
    'Professional MERN/MEVN Stack Developer',
    'Exceptional Full Stack Web Developer',
    'Local freelance talent',
    'Outstanding Front-End Engineer',
    'Best web development services',
    'Reliable freelance developer',
    'Talented React-Native specialist',
    'TypeScript Developer',
    'JavaScript Developer',
    'UI/UX Design',
    'Responsive Design',
    'Remote Developer',
    'Portfolio',
    'Website Development',
    'Web Applications',
    'Tailwind CSS',
    'MongoDB',
    'Express.js',
    'Vue.js',
    'GitHub',
    'Vercel',
    'Netlify',
    'United Kingdom',
    'Available for Hire',
    'Open Source Contributor',
    // European-focused keywords
    'European Freelancer',
    'UK Web Developer',
    'Germany Web Developer',
    'France Web Developer',
    'Netherlands Web Developer',
    'Spain Web Developer',
    'Italy Web Developer',
    'Switzerland Web Developer',
    'Austria Web Developer',
    'Belgium Web Developer',
    'Sweden Web Developer',
    'Norway Web Developer',
    'Denmark Web Developer',
    'Poland Web Developer',
    'Portugal Web Developer',
    'Ireland Web Developer',
    'Remote Developer Europe',
    'EU Freelancer',
    'European Full Stack Developer',
    'React Developer Europe',
    'Next.js Developer Europe',
    'MERN Stack Developer Europe',
    'Freelance Developer Europe',
    'Web Developer Europe',
    'Frontend Developer Europe',
    'International Freelancer',
    'Global Web Developer',
    'Remote Work',
    'International Remote Developer',
  ],
  url: 'https://yashkapure.netlify.app',
  googleSiteVerificationId: 'zjseZ18pLQ6Tg4nvpJJkRVevf7dK4QzbpzMuZNCKNYQ',
  // Supported locales for international SEO
  // en-US first for US traffic; default en for global
  locales: [
    'en',
    'en-US',
    'en-GB',
    'en-IE',
    'en-DE',
    'en-FR',
    'en-ES',
    'en-IT',
    'en-NL',
    'en-BE',
    'en-AT',
    'en-CH',
    'en-SE',
    'en-NO',
    'en-DK',
    'en-PL',
    'en-PT',
  ],
  defaultLocale: 'en',
};
