export const siteConfig = {
  title:
    'Yash Kapure | Best Frontend Services | Front-End Engineer | Full Stack Web Developer | React & Next.js',
  description:
    'Best frontend services: production UIs, React, Next.js, performance, and SEO. Yash Kapure offers Frontend Development, Full Stack, Database, Performance, Architecture, Product UI, and SEO/AEO/GEO. Hire for US & global. $25–57/hr.',
  keywords: [
    'Yash Kapure portfolio',
    'Frontend Engineer',
    'Full Stack Developer',
    'React developer',
    'Next.js developer',
    'TypeScript developer',
    'JavaScript developer',
    'MERN stack developer',
    'MEVN stack developer',
    'Frontend development services',
    'Full stack web development services',
    'Performance optimization',
    'Core Web Vitals optimization',
    'SEO AEO GEO',
    'JSON-LD structured data',
    'Responsive web design',
    'UI engineering',
    'Tailwind CSS',
    'React and Next.js freelancer',
    'Remote web developer',
    'Web developer UK',
    'Web developer US clients',
    'Freelance developer Europe',
    'Portfolio website developer',
    'Open to full-time freelance contract',
  ],
  url: 'https://yashkapure.netlify.app',
  googleSiteVerificationId: 'zjseZ18pLQ6Tg4nvpJJkRVevf7dK4QzbpzMuZNCKNYQ',
};
