export const siteConfig = {
  title:
    'Yash Kapure | Hire Frontend Developer | React & Next.js | US UK EU',
  description:
    'Hire frontend developer for React and Next.js. 4+ years, production UIs and full-stack apps. Freelance for US, UK, and EU clients. TypeScript, MERN/MEVN. $25–57/hr.',
  keywords: [
    'hire frontend developer',
    'react developer for hire',
    'next.js developer for hire',
    'freelance frontend developer',
    'Yash Kapure',
    'React developer',
    'Next.js developer',
    'frontend engineer',
    'remote React developer',
    'freelance React Next.js',
    'MERN stack developer',
    'US UK EU developer',
    'contract frontend developer',
    'TypeScript developer',
    'hire React developer',
    'hire Next.js developer',
    'available for hire',
    'freelance web developer',
    'professional React developer',
    'experienced Next.js developer',
  ],
  url: 'https://www.yashkapure.com',
  googleSiteVerificationId: 'zjseZ18pLQ6Tg4nvpJJkRVevf7dK4QzbpzMuZNCKNYQ',
};
