export const projects = [
    {
      title: 'Anandlok Ayurveda',
      description: "Using ReactJs, Next.js, and Material-UI, I worked as an Intern for Anandlok Ayurveda & Panchakrma Hospital and created a website for Ayurveda & Panchakarma practitioners to share their knowledge and experience with others.",
        image: '/images/1.png',
        tags: ['Next.js', 'React.Js', 'CSS', 'Material-UI'],
        source:'https://github.com/Yashkapure06/anandlokayurveda',
        visit: 'https://www.anandlokayurved.com',
        id: 'anandlokayurveda',
    },
    {
      title: 'OpenSource Contribution in Chakra-UI',
      description: "I created a portfolio website for my OpenSource contribution in Chakra-UI. This website is a collection of my contributions to the Chakra-UI community.",
        image: '/images/9.png',
        tags: ['Chakra-UI', 'React.Js', 'CSS'],
        source:'https://github.com/Yashkapure06/awesome-chakra-ui',
        visit: 'https://chakra-ui.com/community/showcase',
        id: 'anandlokayurveda',
    },
    {
      title: 'Netflix Clone using ReactJs',
      description: "I created a Netflix clone using ReactJs and Sass. This is a clone of Netflix website. And played a lot with Api.",
      image: '/images/10.png',
      tags: ['React JS', 'SCSS', 'CSS', 'API'],
      source: 'https://github.com/Yashkapure06/netflix-clone',
      visit: 'https://netflix-clone-06.netlify.app/',
      id: 'netflix-clone',
  
    },
    {
      title: 'YouTube Clone using ReactJs',
      description: "I created a YouTube clone using ReactJs and Material UI. Used Rapid API to fetch data and learnt how to fetch data using API. The API used here was YouTube v3.",
      image: '/images/11.png',
      tags: ['ReactJs', 'CSS', 'Material-UI', 'API'],
      source: 'https://github.com/Yashkapure06/youtube_clone',
      visit: 'https://youtube-clone-06.netlify.app/',
      id: 'youtube-clone',
  
    },
    {
      title: 'Blogging Website',
      description: "This Blogging Website is made with NodeJs, Express and MongoDB. It is a simple blogging website where you can read, write, delete and edit your blog post. ",
      image: '/images/7.png',
      tags: ['Nodejs', 'Express', 'CSS', 'MongoDB'],
      source: 'https://github.com/Yashkapure06/Blogging-Website',
      visit: 'https://github.com/Yashkapure06/Blogging-Website',
      id: 'bloggingwebsite',
  
    },
    {
      title: 'Personal Portfolio',
      description: "This is my personal portfolio website. I have made this with the help of NextJS + Its documents .You can see my projects, skills, and contact me over here as well. ",
      image: '/images/8.png',
      tags: ['NextJs', 'MaterialUI'],
      source: 'https://github.com/Yashkapure06/PersonalPortfolio',
      visit: 'https://yash-kapure.vercel.app/',
      id: 'personalPortfolio',
  
    },
    {
      title: 'Space Talks ✨',
      description: "This is a MERN Website. I have created this website using ReactJs, Material-UI, Nodejs, CSS, Express and MongoDB. This website is a platform for people to share their love and knowledge about space, universe, stars, galaxies and other planets with people from all over.",
      image: '/images/spacetalks.png',
      tags: ['ReactJs', 'Material-UI', 'Three.Js', 'MongoDB'],
      source: 'https://github.com/Yashkapure06/Space-Talks-MERN',
      visit: 'https://space-talks.netlify.app/',
      id: 'spacetalks',
    },
    {
      title: 'Personal Portfolio',
      description: "This is My 1st Portfolio Website. I Made this with ReactJS while Learning ReactJS. A lots of CSS is Used for Animation. I have also added the feature of Dark & Light Mode",
      image: '/images/4.png',
      tags: ['React', 'CSS3', 'JavaScript'],
      source: 'https://github.com/Yashkapure06/PersonalPortfolio2',
      visit: 'https://yashkapure-portfolio.web.app/',
      id: 'personalportfolio',
    },
    {
      title: 'Movie WebApp',
      description: "A Simple Movie App Using Pure ReactJs - made for just revision purpose",
      image: '/images/6.png',
      tags: ['React', 'CSS3', 'JavaScript', 'API'],
      source: 'https://github.com/Yashkapure06/Movie-App',
      visit: 'https://react-movie-app-yash.netlify.app/',
      id: 'movieapp',
    },
    {
      title: 'Complete React Website',
      description: "I made this whole website from scratch with latest versions of React. This Complete Demo Website is Made using ReactJs, HTML, CSS. This website is a complete demo website which includes all the components of ReactJs.",
        image: '/images/3.png',
        tags: ['React', 'CSS3'],
      source: 'https://github.com/Yashkapure06/React-Website',
      visit: 'https://reactwebsite-3b247.web.app/',
      id: 'reactwebsite',
    },
    {
      title: 'Wedding Invitation Website',
      description: "This Website is purely made with HTML, CSS and mainly JS. You Will find some Beautiful animations in this website. Some Special Features are also added in this website, please visit and check.",
        image: '/images/5.png',
        tags: ['HTML', 'CSS', 'JS'],
      source: 'https://github.com/Yashkapure06/Wedding-Website',
      visit: 'https://harshal-nandani.web.app/',
      id: 'weddingwebsite',
    },
    {
      title: 'ToDo List',
      description:"This project is made with EJS, Nodejs and MongoDB at basic level. It is a simple todo list. For backend I have used MongoDB. Main feature is anyone can use it &  you can play with the link. ",
      image: '/images/2.png',
      tags: ['EJS', 'Nodejs', 'MongoDB'],
      source: 'https://github.com/Yashkapure06/todolist-v1.git',
      visit: 'https://tranquil-stream-68506.herokuapp.com/',
      id: 'todolist',
    },
  ];


  export const testimonials = [
    {
      heading :'Web Development at Anandlok Ayurveda',
      message : 'Yash worked very hard for this project as Intern at Anandlok Ayurveda, Beautifully created the whole website one handedly with proper stack he knows. Wish you all the best for your future.',
      avatar : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd8ykRstebGo9HXF-ZFiHGhj4l6YF_papozO8q5j-8ig&s',
      name : 'Dr. Viraj Gite',
      title: 'CEO at Anandlok Ayurveda Hospital',
      location: 'Nagpur, India',
    },
    {
      heading :'Portfolio development for Assam Client',
      message : 'I saw his portfolio on the chakra UI documentation and liked it so I asked him to make me one. The UI is really eye-catching as well as smooth, he has a very good understanding of the tech stacks that he uses. I wish him all the best for his future projects.',
      avatar : 'https://media-exp1.licdn.com/dms/image/C5603AQGBlcZKMni90w/profile-displayphoto-shrink_100_100/0/1642131536797?e=1667433600&v=beta&t=gIixVC-LW70nSAQJnOKdJsL30ufQN6AfHZgXFqXrq8M',
      name : 'Subham Dey',
      title: 'Student',
      location: 'Assam, India',
    },
  ]