export const projects = [
    {
      title: 'Anandlok Ayurveda',
      description: "Using ReactJs, Next.js, and Material-UI, I worked as an Intern for Anandlok Ayurveda & Panchakrma Hospital and created a website for Ayurveda & Panchakarma practitioners to share their knowledge and experience with others.",
        image: '/images/1.png',
        tags: ['Next.js', 'React.Js', 'CSS', 'Material-UI'],
        source:'https://github.com/Yashkapure06/anandlokayurveda',
        visit: 'https://www.anandlokayurved.com',
        id: 'anandlokayurveda',
    },
    {
      title: 'OpenSource Contribution in Chakra-UI',
      description: "I created a portfolio website for my OpenSource contribution in Chakra-UI. This website is a collection of my contributions to the Chakra-UI community.",
        image: '/images/9.png',
        tags: ['Chakra-UI', 'React.Js', 'CSS'],
        source:'https://github.com/Yashkapure06/awesome-chakra-ui',
        visit: 'https://chakra-ui.com/community/showcase',
        id: 'anandlokayurveda',
    },
    {
      title: 'Blogging Website',
      description: "This Blogging Website is made with NodeJs, Express and MongoDB. It is a simple blogging website where you can read, write, delete and edit your blog post. ",
      image: '/images/7.png',
      tags: ['Nodejs', 'Express', 'CSS', 'MongoDB'],
      source: 'https://github.com/Yashkapure06/Blogging-Website',
      id: 'bloggingwebsite',
  
    },
    {
      title: 'Personal Portfolio',
      description: "This is my personal portfolio website. I have made this with the help of NextJS + Its documents .You can see my projects, skills, and contact me over here as well. ",
      image: '/images/8.png',
      tags: ['NextJs', 'MaterialUI'],
      source: 'https://github.com/Yashkapure06/PersonalPortfolio',
      visit: 'https://yash-kapure.vercel.app/',
      id: 'personalPortfolio',
  
    },
    {
      title: 'Space Talks ✨',
      description: "This is a MERN Website. I have created this website using ReactJs, Material-UI, Nodejs, CSS, Express and MongoDB. This website is a platform for people to share their love and knowledge about space, universe, stars, galaxies and other planets with people from all over.",
      image: '/images/spacetalks.png',
      tags: ['ReactJs', 'Material-UI', 'Three.Js', 'MongoDB'],
      source: 'https://github.com/Yashkapure06/Space-Talks-MERN',
      visit: 'https://space-talks.netlify.app/',
      id: 'spacetalks',
    },
    {
      title: 'Personal Portfolio',
      description: "This is My 1st Portfolio Website. I Made this with ReactJS while Learning ReactJS. A lots of CSS is Used for Animation. I have also added the feature of Dark & Light Mode",
      image: '/images/4.png',
      tags: ['React', 'CSS3', 'JavaScript'],
      source: 'https://github.com/Yashkapure06/PersonalPortfolio2',
      visit: 'https://yashkapure-portfolio.web.app/',
      id: 'personalportfolio',
    },
    {
      title: 'Movie WebApp',
      description: "A Simple Movie App Using Pure ReactJs - made for just revision purpose",
      image: '/images/6.png',
      tags: ['React', 'CSS3', 'JavaScript', 'API'],
      source: 'https://github.com/Yashkapure06/Movie-App',
      visit: 'https://react-movie-app-yash.netlify.app/',
      id: 'movieapp',
    },
    {
      title: 'Complete React Website',
      description: "I made this whole website from scratch with latest versions of React. This Complete Demo Website is Made using ReactJs, HTML, CSS. This website is a complete demo website which includes all the components of ReactJs.",
        image: '/images/3.png',
        tags: ['React', 'CSS3'],
      source: 'https://github.com/Yashkapure06/React-Website',
      visit: 'https://reactwebsite-3b247.web.app/',
      id: 'reactwebsite',
    },
    {
      title: 'Wedding Invitation Website',
      description: "This Website is purely made with HTML, CSS and mainly JS. You Will find some Beautiful animations in this website. Some Special Features are also added in this website, please visit and check.",
        image: '/images/5.png',
        tags: ['HTML', 'CSS', 'JS'],
      source: 'https://github.com/Yashkapure06/Wedding-Website',
      visit: 'https://harshal-nandani.web.app/',
      id: 'weddingwebsite',
    },
    {
      title: 'ToDo List',
      description:"This project is made with EJS, Nodejs and MongoDB at basic level. It is a simple todo list. For backend I have used MongoDB. Main feature is anyone can use it &  you can play with the link. ",
      image: '/images/2.png',
      tags: ['EJS', 'Nodejs', 'MongoDB'],
      source: 'https://github.com/Yashkapure06/todolist-v1.git',
      visit: 'https://tranquil-stream-68506.herokuapp.com/',
      id: 'todolist',
    },
  ];