import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Yash Kapure | Frontend Engineer & Full Stack Expertise',
  description:
    "Hello, I'm Yash Kapure. I am a Full Stack Developer with 3.5+ years of experience in React.js, Next.js, Node.js, and MERN/MEVN stack. I specialize in creating interactive and beautiful user interfaces with modern web technologies.",
  keywords: [
    'Yash Kapure',
    'Frontend Engineer',
    'Full Stack Developer',
    'React Developer',
    'Next.js Developer',
    'Node.js Developer',
    'TypeScript Developer',
    'JavaScript Developer',
    'MERN Stack Developer',
    'MEVN Stack Developer',
    'Web Development',
    'UI/UX Design',
    'Responsive Design',
    'Freelance Developer',
    'Remote Developer',
    'Portfolio',
    'Website Development',
    'Web Applications',
    'Tailwind CSS',
    'MongoDB',
    'Express.js',
    'Vue.js',
    'GitHub',
    'Vercel',
    'Netlify',
    'United Kingdom',
    'Available for Hire',
    'Open Source Contributor',
  ],
  url: env.SITE_URL || 'https://yashkapure.dev',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
