import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Yash Kapure | Frontend Engineer & Full Stack Expertise',
  description:
    "Hello, I'm Yash Kapure. I am a Full Stack Developer with 3.5+ years of experience in React.js, Next.js, Node.js, and MERN/MEVN stack. I specialize in creating interactive and beautiful user interfaces with modern web technologies.",
  keywords: [
    'Yash Kapure',
    'Best Frontend engineer in United Kingdom',
    "United Kingdom's Best Frontend engineer",
    "United Kingdom's Best Full Stack Developer",
    "United Kingdom's Best React Developer",
    "United Kingdom's Best Next.js Developer",
    "United Kingdom's Best Node.js Developer",
    "United Kingdom's Best MERN Stack Developer",
    "United Kingdom's Best MEVN Stack Developer",
    'Full Stack Developer',
    "United Kingdom's Best Full Stack Developer",
    "United Kingdom's Best React Developer",
    "United Kingdom's Best Next.js Developer",
    "United Kingdom's Best Node.js Developer",
    "United Kingdom's Best MERN Stack Developer",
    "United Kingdom's Best MEVN Stack Developer",
    'Frontend Developer',
    'React Developer',
    'Next.js Developer',
    'Node.js Developer',
    'MERN Stack',
    'MEVN Stack',
    'JavaScript Developer',
    'TypeScript Developer',
    'Web Development',
    'UI/UX Design',
    'Responsive Design',
    'SEO Specialist',
    'Freelancer',
    'Portfolio',
    'Projects',
    'Website Development',
    'Web Applications',
    'Mobile App Development',
    'React Native',
    'MongoDB',
    'Express.js',
    'Vue.js',
    'Tailwind CSS',
    'Material-UI',
    'Chakra UI',
    'Git',
    'GitHub',
    'Heroku',
    'Vercel',
    'Netlify',
    'India',
    'Nagpur',
    'Pune',
    'Remote Work',
    'Available for Hire',
    'Tech Enthusiast',
    'Open Source Contributor',
  ],
  url: env.SITE_URL || 'https://yashkapure.dev',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
