import { env } from '@/env.mjs';

export const siteConfig = {
  title:
    'Yash Kapure | Best Freelancer | Front-End Engineer | MERN/MEVN Stack Dev | Full Stack Web Developer | React-Native Developer',
  description:
    'Hi there! My name is Yash and I am a programmer with a passion for learning and exploring new technologies. With a strong background in full-stack development, I have a well-rounded skill set and am always looking to expand my knowledge and take on new challenges. As a dedicated and driven individual, I am constantly seeking out opportunities to grow and improve as a programmer.',
  keywords: [
    'Online Interview Assessment System for Students and Professionals',
    'Yash Kapure projects',
    'Projects by Yash Kapure',
    'Yash Kapure',
    'Contact Yash Kapure',
    "Dr. Manisha's Yoga Institute is Developed by Yash Kapure",
    'Anandlok Ayurveda is Developed By Yash Kapure',
    'Anandlok Ayurveda',
    "Dr. Manisha's Yoga Institute",
    'Projects of Yash Kapure',
    'Best Freelancer Near me',
    'Affordable Freelancer Near me',
    'Hourly based paid freelancer near me',
    'React-Native Developer near me',
    'React.js Developer Near me',
    'Next.js Developer Near me',
    'Yash Vinod Kapure',
    'Best Freelancer',
    'Front-End Engineer',
    'MERN/MEVN Stack Dev',
    'Full Stack Web Developer',
    'Front-end React-Native Developer',
    'Freelance web development',
    'React-Native development services',
    'MERN Stack projects',
    'MEVN Stack development',
    'Web development portfolio',
    'Yash Kapure portfolio',
    'Freelancer services',
    'Full Stack Developer',
    'Who is Yash Kapure?',
    'Where does yash Kapure Live?',
    'Web Developer Near me',
    'Front-End Developer near me',
    'Domain Name purchase',
    'Top-rated freelancer',
    'Expert web developer',
    'Skilled React-Native Developer',
    'Professional MERN/MEVN Stack Developer',
    'Exceptional Full Stack Web Developer',
    'Local freelance talent',
    'Outstanding Front-End Engineer',
    'Best web development services',
    'Reliable freelance developer',
    'Talented React-Native specialist',
    'TypeScript Developer',
    'JavaScript Developer',
    'UI/UX Design',
    'Responsive Design',
    'Remote Developer',
    'Portfolio',
    'Website Development',
    'Web Applications',
    'Tailwind CSS',
    'MongoDB',
    'Express.js',
    'Vue.js',
    'GitHub',
    'Vercel',
    'Netlify',
    'United Kingdom',
    'Available for Hire',
    'Open Source Contributor',
  ],
  url: env.SITE_URL || 'https://yash-kapure.vercel.app',
  googleSiteVerificationId:
    env.GOOGLE_SITE_VERIFICATION_ID ||
    'zjseZ18pLQ6Tg4nvpJJkRVevf7dK4QzbpzMuZNCKNYQ',
};
